version: 0.2
phases:
  install:
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - python -m pytest --cov=src/ --cov-fail-under 100 tests/
  build:
    commands:
artifacts:
